#ifndef CWK1_BOOK_MANAGEMENT_H
#define CWK1_BOOK_MANAGEMENT_H

#include <stdio.h>

/*You can extend the structs (Book and BookList) defined in this head file;
  However, you may not change the function prototypes.
  You are also free to add additional head files and data structures as needed.
*/



typedef struct _Book {
    unsigned int id; //Book ID
    char *title; //book title
    char *authors; //comma separated list of authors
    unsigned int year; // year of publication
    unsigned int copies; //number of copies the library has
    struct _Book *next; //pointer to the next book element
}Book;

typedef struct _Book *linklist;


typedef struct _BookList {
    Book* list; // pointer to a list of struct Book.
    unsigned int length; // number of elements in the (Book*) List
}BookList;

typedef struct _BookList *list;

void books();
void output_books(linklist head);
void librarian();

//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_books(FILE *file, linklist head);//w

//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_books(FILE *file);//r
//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
//int add_book(Book book);
int add_book(linklist head);


//removes a book from the library
//returns 0 if the book could be successfully removed, or an error code otherwise.
//int remove_book(Book book);
int remove_book(linklist head);

//finds books with a given title.
//returns a BookList structure, where the field "list" is a list of books, or null if no book with the
//provided title can be found. The length of the list is also recorded in the returned structure, with 0 in case
//list is the NULL pointer.
BookList find_book_by_title (const char *title, linklist head);
//BookList find_book_by_title (linklist head);

//finds books with the given authors.
//returns a Booklist structure, where the field "list" is a newly allocated list of books, or null if no book with the
//provided title can be found. The length of the list is also recorded in the returned structure, with 0 in case
//list is the NULL pointer.
BookList find_book_by_author (const char *author, linklist head);
//BookList find_book_by_author (linklist head);

//finds books published in the given year.
//returns a Booklist structure, where the field "list" is a list of books, or null if no book with the
//provided title can be found. The length of the list is also recorded in the returned structure, with 0 in case
//list is the NULL pointer.
BookList find_book_by_year (unsigned int year, linklist head);

void search();
void return_book(char *uuu, linklist head);
int load(FILE*file);//struct without copies, used by users.
int store(FILE*file, linklist head);//struct without copies, used by users.

#endif
